wandb_version: 1

batch_size:
  value: 64
channel_sizes:
  value:
  - 512
  - 512
  - 512
dropout:
  value: 0.4
epochs:
  value: 50
fc_layer_sizes:
  value:
  - 64
learning_rate:
  value: 0.0005
optimizer:
  value: adam
